name: Build and Test

# Триггеры для запуска CI/CD пайплайна
on:
  push:
    branches: [ main ]  # Запускать при пуше в ветку main
  pull_request:
    branches: [ main ]  # Запускать при создании PR в ветку main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Выполнять на последней версии Ubuntu

    # Настраиваем сервисы, необходимые для тестирования
    services:
      postgres:
        image: postgres:14-alpine  # Используем PostgreSQL 14 на Alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: userservice
        ports:
          - 5432:5432  # Проброс порта PostgreSQL
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Шаг 1: Получение кода из репозитория
      - uses: actions/checkout@v3

      # Шаг 2: Настройка Go версии 1.20
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Шаг 3: Сборка Docker образа
      - name: Build Docker image
        run: docker build -t user-microservice .

      # Шаг 4: Запуск Docker контейнера для тестирования
      - name: Run Docker container
        run: |
          # Проверка наличия запущенных контейнеров на порту 8080
          echo "Checking for existing services on port 8080:"
          sudo netstat -tulpn | grep 8080 || echo "No services on port 8080"
          
          # Запуск контейнера с опцией --add-host
          docker run -d -p 8080:8080 \
            -e POSTGRES_HOST=host.docker.internal \
            -e POSTGRES_PORT=5432 \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -e POSTGRES_DB=userservice \
            --add-host=host.docker.internal:host-gateway \
            --name user-service user-microservice
          
          echo "Waiting for container to start up..."
          sleep 30  # Увеличиваем время ожидания
          
          echo "Container status:"
          docker ps -a
          
          echo "Container logs:"
          docker logs user-service
          
          echo "Network check:"
          curl -v http://localhost:8080/ || echo "Expected 404, continuing..."
          
          # Проверка подключения к базе данных из контейнера
          echo "Testing database connectivity from container:"
          # Убираем флаг -t, который вызывает ошибку в CI среде
          docker exec -i user-service sh -c "nc -zv host.docker.internal 5432 || echo 'DB connection failed'"
          
          # Пробуем добавить запись в журнал для диагностики
          docker exec -i user-service cat /var/log/userservice/app.log || echo "Cannot read logs"
          
          # Проверка доступности сервиса внутри контейнера
          docker exec -i user-service curl -v localhost:8080 || echo "Service not accessible inside container"

      # Шаг 5: Запуск тестов Go
      - name: Run API Tests
        run: |
          echo "Running Go API tests..."
          # Modify tests to wait longer for API
          sed -i 's/maxRetries := 5/maxRetries := 15/' ./tests/api_test.go
          sed -i 's/retryInterval := 2 \* time.Second/retryInterval := 4 \* time.Second/' ./tests/api_test.go
          # Добавляем переменные окружения для тестов
          export API_URL=http://localhost:8080
          
          # Запуск тестов с таймаутом
          go test -timeout 2m -v ./tests

      # Шаг 6: Аутентификация в Docker Hub (только для ветки main)
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Шаг 7: Публикация образа в Docker Hub (только для ветки main)
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-microservice:latest
